- name: user module demo
  hosts: user
  become: true
  tasks:
    - name: create user
      ansible.builtin.user:
        name: user1
        password: "{{ 'password' | password_hash('sha512', 'mysecretpassword') }}"
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/user1"
        comment: "Ansible user1"
    - name: Creates directory
      file:
        path: /home/user1/.ssh
        state: directory
    - name: Copy private key
      copy:
        src: Key/id_rsa
        dest: /home/user1/.ssh/id_rsa
        decrypt: yes
        owner: user1 
        group: user1
        backup: no
    - name: Copy public key
      copy:
        src: Key/id_rsa.pub    
        dest: /home/user1/.ssh/id_rsa.pub      
        decrypt: yes
        owner: user1
        group: user1 
        backup: no
